version: '3'
services: 
  db:
    image: postgres:latest
    container_name: split-money-db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=split-money
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres